import React, { Suspense } from "react";
import Carousel from "@/components/Carousel";
import Header from "@/components/Header";
import TopDescription from "@/components/TopDescription";
import Head from "next/head";
import Script from "next/script";
import Container from "react-bootstrap/Container";
import { Spinner } from "react-bootstrap";

const Pricing = React.lazy(() => import("@/components/Pricing"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Echo Wilpatthu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />
        <link
          href="https://getbootstrap.com/docs/5.3/assets/css/docs.css"
          rel="stylesheet"
        />
      </Head>
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        strategy="afterInteractive"
      />
      <Container as="main" className="py-4 px-3 mx-auto">
        <h1>Welcome to Echo Wilpatthu</h1>
        <TopDescription />
        <hr className="col-1 my-5 mx-0" />
        <Carousel />
        <Suspense
          fallback={
            <div className="d-flex justify-content-center my-5">
              <Spinner animation="border" role="status">
                <span className="visually-hidden">Loading...</span>
              </Spinner>
            </div>
          }
        >
          <Pricing />
        </Suspense>
      </Container>
    </>
  );
}
